name: Build

on: [ push, pull_request ]

jobs:
  build:
    name: Build
    runs-on: macos-latest

    steps:
      - name: Chceckout code
        uses: actions/checkout@v2
      - name: Cache cargo
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-debug-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-debug-
      - name: Run linter
        run: cargo clippy --all-features -- -D warnings
      - name: Run tests
        env:
          TEST_BACA_PASSWORD: ${{ secrets.TEST_BACA_PASSWORD }}
          TEST_BACA_LOGIN: ${{ secrets.TEST_BACA_LOGIN }}
          TEST_BACA_HOST: ${{ secrets.TEST_BACA_HOST }}
          AUTH_TOKEN: ${{ secrets.AUTH_TOKEN }}
        run: cargo test

  formatting:
    name: Formatting
    runs-on: macos-latest

    steps:
      - name: Chceckout code
        uses: actions/checkout@v2
      - name: Check formatting
        run: cargo fmt --all -- --check
