name: Build

on: [ push ]

jobs:
  build:
    name: Build
    runs-on: macos-latest

    steps:
      - name: Chceckout code
        uses: actions/checkout@v2
      - name: Cache cargo
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-debug-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-debug-
      - name: Run linter
        run: cargo clippy --all-features -- -D warnings

  formatting:
    name: Formatting
    runs-on: macos-latest

    steps:
      - name: Chceckout code
        uses: actions/checkout@v2
      - name: Check formatting
        run: cargo fmt --all -- --check
